### ISSUE TITLE
thumbnail for cart

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/alala-carte#12]
can we use the final color selections? or i can design a placeholder we use universally

<img width="361" alt="screen shot 2016-04-17 at 9 00 24 pm" src="https://cloud.githubusercontent.com/assets/3649059/14591438/a11bc192-04df-11e6-8366-dfeccaae3de1.png">

**Comment by EmilioTelevision** [comment]
a place holder would be best for now, then I can look into that

**Comment by EmilioTelevision** [comment]
for now its the product image, no panels  
![image](https://cloud.githubusercontent.com/assets/3394886/14622966/f14336a2-059b-11e6-819b-7ee8f1d8bbaf.png)
