### ISSUE TITLE
reposition layers

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/alala-carte#14]
they got shifted when i switched up the grid
<img width="502" alt="screen shot 2016-04-18 at 5 11 40 am" src="https://cloud.githubusercontent.com/assets/3649059/14599231/24774a72-0524-11e6-84c8-c64c4d56f021.png">

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/14609934/d27c2a7c-0559-11e6-883d-dc4f65a781d5.png)
