### ISSUE TITLE
product description

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/alala-carte#16]
Need some copy to go here - should be different than standard Captain tight description

<img width="1402" alt="screen shot 2016-04-18 at 1 23 03 pm" src="https://cloud.githubusercontent.com/assets/3649059/14613100/b66d0586-0568-11e6-9a3f-d65ebb07d6a2.png">

**Comment by alalamama** [comment]
hi ho

**Comment by alalamama** [comment]
A TIGHT THAT'S AS SPECIAL AS YOU ARE 
This is what you're been waiting for. 
Finally, a one of a kind design that you can call your own. 
This is All You. This is Alala Carte. 

Free Shipping on all orders of Alala Carte tights 
Inseam: 27.5" 
Fabrics are wicking and machine washable 
Flat lock anti-chafe seaming 
Optional silver reflective heat transfer monogram 

All Alala Carte products are made to order. Kindly allow 4-6 weeks for delivery. Unfortunately we cannot accept exchanges or returns for this item at this time.
