### ISSUE TITLE
lower panel open

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/alala-carte#18]
when lower panel menu is open, its swalllowing up the padding on monogram title
should be about 25px of room above "monogram"
<img width="448" alt="screen shot 2016-04-19 at 11 51 03 am" src="https://cloud.githubusercontent.com/assets/3649059/14645847/4763d97c-0625-11e6-89d9-379a15cebd70.png">
<img width="446" alt="screen shot 2016-04-19 at 11 50 59 am" src="https://cloud.githubusercontent.com/assets/3649059/14645865/557aa39c-0625-11e6-8b55-a447e004e680.png">

vertical spacing should be more balanced, like this example -
<img width="379" alt="screen shot 2016-04-19 at 11 55 27 am" src="https://cloud.githubusercontent.com/assets/3649059/14645934/a882e248-0625-11e6-866e-db4f4094f5a6.png">

**Comment by EmilioTelevision** [comment]
fixed 
![image](https://cloud.githubusercontent.com/assets/3394886/14650362/7e687536-0639-11e6-80f9-4f19ce669482.png)
