### ISSUE TITLE
Value Edits

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/alala-carte#19]
**Monogram Description** - please change to:
located on black right ankle
<img width="387" alt="screen shot 2016-04-19 at 12 07 31 pm" src="https://cloud.githubusercontent.com/assets/3649059/14646397/55e7f2ce-0627-11e6-8c91-d1f0bad8bdff.png">

***_Form Field ***_\- please change go:
Enter up to 3 characters (Letters and numbers only)
<img width="385" alt="screen shot 2016-04-19 at 12 09 18 pm" src="https://cloud.githubusercontent.com/assets/3649059/14646478/9680bfaa-0627-11e6-91cf-48fbf7017313.png">

on 156, i set the pattern value to only accept letters. please change so it accepts numbers as well, but no other characters like @!$%^&*

<img width="804" alt="screen shot 2016-04-19 at 12 11 45 pm" src="https://cloud.githubusercontent.com/assets/3649059/14646593/0e454880-0628-11e6-8cc7-4c25520f4c65.png">

**Comment by EmilioTelevision** [comment]
had to write code to detect and prevent anything other then text or numbers. should be all good
