### ISSUE TITLE
display name of swatch color selected

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/alala-carte#2]

**Comment by GVFTW** [comment]
<img width="411" alt="screen shot 2016-04-15 at 4 45 06 am" src="https://cloud.githubusercontent.com/assets/3649059/14556187/d964b9cc-02c4-11e6-8399-72d0d5271088.png">

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/14627589/d281fe74-05c3-11e6-85be-6c14b6456990.png)
 still have to clean up code so the previous panels value doesnt show
