### ISSUE TITLE
Testing Thread

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/alala-carte#23]
Now that we're live, lets put any bugs here. Add a comment, then just edit your comment rather than writing a new one to make it easier to read.

Please use screenshots and language to be as specific as possible

**Comment by GVFTW** [comment]
Nav Bar not resizing
<img width="399" alt="screen shot 2016-04-20 at 7 10 26 pm" src="https://cloud.githubusercontent.com/assets/3649059/14693312/aee7d704-072b-11e6-8a45-ba061a687a79.png">
<img width="1336" alt="screen shot 2016-04-20 at 7 09 39 pm" src="https://cloud.githubusercontent.com/assets/3649059/14693318/b3ad27bc-072b-11e6-8882-3bfd92734646.png">

**Comment by cascadiaderek** [comment]
Nav bar seems to be resizing but the transition is going slow.  Investigating further...

**Comment by cascadiaderek** [comment]
Summer Palm Print when applied to Lower Panel is not aligned (see screenshot of black stripe on inner calve).  All other swatches are aligned.

![screen shot 2016-04-20 at 5 09 52 pm](https://cloud.githubusercontent.com/assets/17285350/14694229/39e28d9c-071b-11e6-82d8-34557a391985.png)

**Comment by EmilioTelevision** [comment]
Remember chrome handless viewport differently. Resizing is not the same as a device

fixed 
![image](https://cloud.githubusercontent.com/assets/3394886/14694649/922ce548-0738-11e6-9df7-dedf26fb2dd4.png)

**Comment by alalamama** [comment]
YELLOW MESH SIDE VIEW NOT SHOWING UP

**Comment by alalamama** [comment]
lower panel WHITE back view is showing up as Summer Palm

**Comment by alalamama** [comment]
<img width="523" alt="screen shot 2016-04-20 at 8 38 39 pm" src="https://cloud.githubusercontent.com/assets/18536527/14694602/e9ec0940-0737-11e6-9c60-190c05244519.png">
alighnment off

**Comment by EmilioTelevision** [comment]
I have to double check swatches. no images are aligned, they fall in place like a puzzle. This is the wrong  panel for this retouch i think

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/14694719/341b88f0-0739-11e6-959d-dc1093317197.png)
yellow mesh
![image](https://cloud.githubusercontent.com/assets/3394886/14694726/450dcca4-0739-11e6-9fe2-7811a0ce9a1c.png)

white lower

**Comment by cascadiaderek** [comment]
Yellow Mesh - Side View: Missing

![screen shot 2016-04-20 at 5 50 37 pm](https://cloud.githubusercontent.com/assets/17285350/14694756/72312c1c-0720-11e6-9394-67ff151449b0.png)

**Comment by cascadiaderek** [comment]
Army Top Panel - Rear View: Appears to be shifted up

![screen shot 2016-04-20 at 5 52 37 pm](https://cloud.githubusercontent.com/assets/17285350/14694782/b4750c56-0720-11e6-9fed-99d3d19f01c9.png)

**Comment by EmilioTelevision** [comment]
yellow fixed 
![image](https://cloud.githubusercontent.com/assets/3394886/14694828/6342d1dc-073a-11e6-8277-1710b0aa829a.png)

**Comment by alalamama** [comment]
URGENT & FIRST PRIORITY --- EVERY Person who was testing this for me last night ran into this issue at some point :::::: 

on mobile --- when u finish all 3 panels 1-2-3. but then go back and try to change upper or mesh, the screen slides over and doesnt come back to center. have to refresh and start over -- on SOME combos only. others work ok 
![img_8926](https://cloud.githubusercontent.com/assets/18536527/14695105/d3a5c07c-073c-11e6-95eb-78ad5d2039b9.PNG)

**Comment by cascadiaderek** [comment]
A solution has been found and is being implemented now

**Comment by EmilioTelevision** [comment]
added correct black  mesh panel on side view 
![image](https://cloud.githubusercontent.com/assets/3394886/14785661/efc1324c-0ac9-11e6-886d-93b377c40da6.png)

**Comment by EmilioTelevision** [comment]
army back panel view fixed
![image](https://cloud.githubusercontent.com/assets/3394886/14785965/e238134c-0aca-11e6-8042-a4f9a7626b45.png)

**Comment by EmilioTelevision** [comment]
the nav responsiveness is tied to shopify's grid framwork. No edits were made to navbar responsiveness

**Comment by GVFTW** [comment]
i noticed it was doing this on your fitness-fashion, but not on ours prior to the theme swap.

check out how low the nav hangs. it eventually goes back up, but only after a minute or so

<img width="375" alt="screen shot 2016-04-25 at 1 13 37 pm" src="https://cloud.githubusercontent.com/assets/3649059/14792299/9ee17904-0ae7-11e6-8b08-f35fc9804324.png">

**Comment by EmilioTelevision** [comment]
Check it now

**Comment by cascadiaderek** [comment]
Just went through and isolated the listed issues:

Nav Responsiveness - FIXED
Correct Images for Views - FIXED
Screen shift bug - FIXED

Closing this ticket....
