### ISSUE TITLE
fix screen shifting bug

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/alala-carte#4]
<img width="1279" alt="screen shot 2016-04-15 at 4 43 05 am" src="https://cloud.githubusercontent.com/assets/3649059/14556150/9c702074-02c4-11e6-9a32-efd018b24d56.png">

**Comment by EmilioTelevision** [comment]
can you describe how to see this bug please

**Comment by GVFTW** [comment]
seems to be resolved on desktop
on mobile, choose lower panel > citrine and entire page slides over

<img width="381" alt="screen shot 2016-04-18 at 4 40 16 pm" src="https://cloud.githubusercontent.com/assets/3649059/14619240/8919a730-0584-11e6-8fa7-8b7fee3a8dff.png">

**Comment by cascadiaderek** [comment]
Also happens in desktop view.  Load page, open mesh panel, click yellow, click yellow again.

**Comment by EmilioTelevision** [comment]
there is some weird javascript going on, once I find i can fix this

**Comment by GVFTW** [comment]
select upper panel > cocoa 2 or 3 times and it happens

**Comment by EmilioTelevision** [comment]
finally fixed this pain in the ass!!

**Comment by cascadiaderek** [comment]
Closing this ticket...
