### ISSUE TITLE
monogram field: show descriptive text, no peekaboo

### ISSUE THREAD

**Issue by GVFTW** [GVFTW/alala-carte#6]
1. expanding lower panel menu, should bump down monogram label a bit

<img width="546" alt="screen shot 2016-04-18 at 4 46 56 am" src="https://cloud.githubusercontent.com/assets/3649059/14598926/9f929e70-0522-11e6-8335-b0616e560e7e.png">
1. descriptive text should always be visible, no peekaboo
   <img width="575" alt="screen shot 2016-04-18 at 5 02 44 am" src="https://cloud.githubusercontent.com/assets/3649059/14598982/df982d0a-0522-11e6-89ad-5f87d9bdccbd.png">

**Comment by EmilioTelevision** [comment]
![image](https://cloud.githubusercontent.com/assets/3394886/14610165/c16f5f3c-055a-11e6-92e9-914c1d2a049c.png)
